[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.2"
opentelemetry = "0.17"
rocket-tracing-opentelemetry = { path = ".." }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
