[package]
name = "rocket-tracing-opentelemetry"
version = "0.1.0"
edition = "2021"

[dependencies]
http = "0.2"
opentelemetry = "0.17"
opentelemetry-http = "0.6"
rocket = "0.5.0-rc.2"
tracing = "0.1"
tracing-opentelemetry = "0.17"
